#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/river

PRODUCT_COPY_FILES += \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/river/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets.rc \
    vendor/motorola/river/proprietary/vendor/etc/init/init.ets.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.ets.rc \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_boe_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_boe_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_h_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_h_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tianma_n_1080p_624.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tianma_n_1080p_624.xml \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_haptic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_haptic.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Argo_Navis.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Argo_Navis.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Attentive.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Attentive.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Awake.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Awake.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Bird_Loop.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Bird_Loop.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Brilliant_Times.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Brilliant_Times.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Chimey_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Chimey_Phone.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Complex.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Complex.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Crazy_Dream.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Crazy_Dream.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Curve_Ball_Blend.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Curve_Ball_Blend.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Digital_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Digital_Phone.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Electrovision.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Electrovision.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Ether_Shake.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Ether_Shake.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Fateful_Words.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Fateful_Words.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Flutey_Phone.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Flutey_Phone.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Future_Funk.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Future_Funk.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Future_Hi_Tech.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Future_Hi_Tech.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Girtab.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Girtab.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Hello.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Hello.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Hexagon.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Hexagon.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Hydra.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Hydra.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Insert_Coin.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Insert_Coin.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Jumping_Dots.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Jumping_Dots.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Keys.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Keys.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Loopy.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Loopy.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Loopy_Lounge.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Loopy_Lounge.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Modular.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Modular.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Momentum.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Momentum.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Morning.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Morning.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Moto.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Moto.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Natural.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Natural.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_New_Player.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_New_Player.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Onward.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Onward.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Organ_Dub.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Organ_Dub.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Overclocked.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Overclocked.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Pegasus.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Pegasus.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Pyxis.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Pyxis.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Regrade.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Regrade.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Scarabaeus.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Scarabaeus.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Sceptrum.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Sceptrum.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Simple.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Simple.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Solarium.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Solarium.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Sparse.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Sparse.bin \
    vendor/motorola/river/proprietary/vendor/firmware/aw869x_rtp_Terrabytes.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw869x_rtp_Terrabytes.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/motorola/river/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx0.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx1.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx2.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx3.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx4.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx5.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx6.bin \
    vendor/motorola/river/proprietary/vendor/firmware/crus_sp_rx7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crus_sp_rx7.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali-na.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali-na.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-cali.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-diag.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-diag.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-na.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-na.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.bin \
    vendor/motorola/river/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/himax-boe-hx83112a-0a05-208-river.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-boe-hx83112a-0a05-208-river.bin \
    vendor/motorola/river/proprietary/vendor/firmware/himax-boe-hx83112a-river.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-boe-hx83112a-river.csv \
    vendor/motorola/river/proprietary/vendor/firmware/himax-tianmah-hx83112a-0500-208-river.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-tianmah-hx83112a-0500-208-river.bin \
    vendor/motorola/river/proprietary/vendor/firmware/himax-tianmah-hx83112a-river.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-tianmah-hx83112a-river.csv \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp1-ultrasound.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp1-ultrasound.bin \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp1-ultrasound.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp1-ultrasound.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp2-aov-frontend.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp2-aov-frontend.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp2-aov-vrgain.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp2-aov-vrgain.bin \
    vendor/motorola/river/proprietary/vendor/firmware/marley-dsp3-aov-control.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/marley-dsp3-aov-control.wmfw \
    vendor/motorola/river/proprietary/vendor/firmware/novatek_ts-tianman-NT36672A-181127-0b-river.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-tianman-NT36672A-181127-0b-river.bin

PRODUCT_PACKAGES += \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmcf-qc-fd-offline \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libtinyalsa-moto \
    sensors.ssc \
    audio.primary.msm8953-moto \
    camera.msm8953 \
    lib_motsensorlistener \
    libactuator_dw9763 \
    libactuator_dw9767 \
    libactuator_lc898217xh \
    libadm \
    libcdsprpc \
    libchromatix_mot_ov12a10_common \
    libchromatix_mot_ov12a10_cpp_hfr_120 \
    libchromatix_mot_ov12a10_cpp_hfr_60 \
    libchromatix_mot_ov12a10_cpp_liveshot \
    libchromatix_mot_ov12a10_cpp_preview \
    libchromatix_mot_ov12a10_cpp_snapshot \
    libchromatix_mot_ov12a10_cpp_snapshot_custom \
    libchromatix_mot_ov12a10_cpp_snapshot_downscale \
    libchromatix_mot_ov12a10_cpp_video \
    libchromatix_mot_ov12a10_default_video \
    libchromatix_mot_ov12a10_hfr_120 \
    libchromatix_mot_ov12a10_hfr_120_3a \
    libchromatix_mot_ov12a10_hfr_60 \
    libchromatix_mot_ov12a10_hfr_60_3a \
    libchromatix_mot_ov12a10_postproc \
    libchromatix_mot_ov12a10_preview \
    libchromatix_mot_ov12a10_snapshot \
    libchromatix_mot_ov12a10_zsl_preview_3a \
    libchromatix_mot_ov12a10_zsl_video_3a \
    libchromatix_mot_s5k3l6_common \
    libchromatix_mot_s5k3l6_cpp_hfr_120 \
    libchromatix_mot_s5k3l6_cpp_hfr_60 \
    libchromatix_mot_s5k3l6_cpp_liveshot \
    libchromatix_mot_s5k3l6_cpp_preview \
    libchromatix_mot_s5k3l6_cpp_snapshot \
    libchromatix_mot_s5k3l6_cpp_snapshot_custom \
    libchromatix_mot_s5k3l6_cpp_video_full \
    libchromatix_mot_s5k3l6_hfr_120 \
    libchromatix_mot_s5k3l6_hfr_120_3a \
    libchromatix_mot_s5k3l6_hfr_60 \
    libchromatix_mot_s5k3l6_hfr_60_3a \
    libchromatix_mot_s5k3l6_postproc \
    libchromatix_mot_s5k3l6_snapshot \
    libchromatix_mot_s5k3l6_video_full \
    libchromatix_mot_s5k3l6_zsl_preview_3a \
    libchromatix_mot_s5k3l6_zsl_video_3a \
    libchromatix_mot_s5k4h7_common \
    libchromatix_mot_s5k4h7_cpp_hfr_120 \
    libchromatix_mot_s5k4h7_cpp_liveshot \
    libchromatix_mot_s5k4h7_cpp_preview \
    libchromatix_mot_s5k4h7_cpp_snapshot \
    libchromatix_mot_s5k4h7_cpp_snapshot_custom \
    libchromatix_mot_s5k4h7_cpp_video_full \
    libchromatix_mot_s5k4h7_hfr_120 \
    libchromatix_mot_s5k4h7_hfr_120_3a \
    libchromatix_mot_s5k4h7_postproc \
    libchromatix_mot_s5k4h7_snapshot \
    libchromatix_mot_s5k4h7_video_full \
    libchromatix_mot_s5k4h7_zsl_preview_3a \
    libchromatix_mot_s5k4h7_zsl_video_3a \
    libchromatix_mot_s5k5e9_common \
    libchromatix_mot_s5k5e9_cpp_hfr_120 \
    libchromatix_mot_s5k5e9_cpp_hfr_60 \
    libchromatix_mot_s5k5e9_cpp_liveshot \
    libchromatix_mot_s5k5e9_cpp_preview \
    libchromatix_mot_s5k5e9_cpp_snapshot \
    libchromatix_mot_s5k5e9_cpp_snapshot_custom \
    libchromatix_mot_s5k5e9_cpp_snapshot_downscale \
    libchromatix_mot_s5k5e9_cpp_video_full \
    libchromatix_mot_s5k5e9_hfr_120 \
    libchromatix_mot_s5k5e9_hfr_120_3a \
    libchromatix_mot_s5k5e9_hfr_60 \
    libchromatix_mot_s5k5e9_hfr_60_3a \
    libchromatix_mot_s5k5e9_postproc \
    libchromatix_mot_s5k5e9_snapshot \
    libchromatix_mot_s5k5e9_video_full \
    libchromatix_mot_s5k5e9_zsl_preview_3a \
    libchromatix_mot_s5k5e9_zsl_video_3a \
    libchromatix_ov12a10_ocean_common \
    libchromatix_ov12a10_ocean_cpp_hfr_120 \
    libchromatix_ov12a10_ocean_cpp_hfr_60 \
    libchromatix_ov12a10_ocean_cpp_liveshot \
    libchromatix_ov12a10_ocean_cpp_preview \
    libchromatix_ov12a10_ocean_cpp_snapshot \
    libchromatix_ov12a10_ocean_cpp_snapshot_custom \
    libchromatix_ov12a10_ocean_cpp_snapshot_downscale \
    libchromatix_ov12a10_ocean_cpp_video \
    libchromatix_ov12a10_ocean_default_video \
    libchromatix_ov12a10_ocean_hfr_120 \
    libchromatix_ov12a10_ocean_hfr_120_3a \
    libchromatix_ov12a10_ocean_hfr_60 \
    libchromatix_ov12a10_ocean_hfr_60_3a \
    libchromatix_ov12a10_ocean_postproc \
    libchromatix_ov12a10_ocean_preview \
    libchromatix_ov12a10_ocean_snapshot \
    libchromatix_ov12a10_ocean_zsl_preview_3a \
    libchromatix_ov12a10_ocean_zsl_video_3a \
    libchromatix_s5k4h7_channel_common \
    libchromatix_s5k4h7_channel_cpp_hfr_120 \
    libchromatix_s5k4h7_channel_cpp_liveshot \
    libchromatix_s5k4h7_channel_cpp_preview \
    libchromatix_s5k4h7_channel_cpp_snapshot \
    libchromatix_s5k4h7_channel_cpp_snapshot_custom \
    libchromatix_s5k4h7_channel_cpp_video_full \
    libchromatix_s5k4h7_channel_hfr_120 \
    libchromatix_s5k4h7_channel_hfr_120_3a \
    libchromatix_s5k4h7_channel_postproc \
    libchromatix_s5k4h7_channel_snapshot \
    libchromatix_s5k4h7_channel_video_full \
    libchromatix_s5k4h7_channel_zsl_preview_3a \
    libchromatix_s5k4h7_channel_zsl_video_3a \
    libchromatix_s5k4h7_ocean_common \
    libchromatix_s5k4h7_ocean_cpp_hfr_120 \
    libchromatix_s5k4h7_ocean_cpp_liveshot \
    libchromatix_s5k4h7_ocean_cpp_preview \
    libchromatix_s5k4h7_ocean_cpp_snapshot \
    libchromatix_s5k4h7_ocean_cpp_snapshot_custom \
    libchromatix_s5k4h7_ocean_cpp_video_full \
    libchromatix_s5k4h7_ocean_hfr_120 \
    libchromatix_s5k4h7_ocean_hfr_120_3a \
    libchromatix_s5k4h7_ocean_postproc \
    libchromatix_s5k4h7_ocean_snapshot \
    libchromatix_s5k4h7_ocean_video_full \
    libchromatix_s5k4h7_ocean_zsl_preview_3a \
    libchromatix_s5k4h7_ocean_zsl_video_3a \
    libdapparamstorage \
    libdepthmapwrapper \
    libflash_pmic \
    libgralloc1 \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_depth_map \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_mot_dw9763_eeprom \
    libmmcamera_mot_dw9767_eeprom \
    libmmcamera_mot_gt24p64b_eeprom \
    libmmcamera_mot_ov12a10 \
    libmmcamera_mot_ov12a10_eeprom \
    libmmcamera_mot_s5k3l6 \
    libmmcamera_mot_s5k5e9 \
    libmmcamera_mot_s5k5e9_eeprom \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k4h7 \
    libmmcamera_s5k4h7_eeprom \
    libmmcamera_sat_test_lib \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_vstab_module \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmot_afd \
    libmot_gpu_mapper \
    libmot_lux_standardization \
    libmotaudioutils \
    libmotimager_utils \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libsensorndkbridge \
    libtinycompress_vendor \
    libunshorten \
    libmmieffectswrapper \
    libspeakerbundle \
    libswdap \
    vendor.dolby.hardware.dms@1.0 \
    libets_fp_et5 \
    libets_teeclient \
    libpn553_fw \
    vendor.egistec.hardware.fingerprint@2.0 \
    charge_only_mode \
    android.hardware.biometrics.fingerprint@2.1-service-ets
